name: limsim_plus
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.12.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=23.3.1
  - python=3.8.10
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - aiofiles==23.2.1
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - altair==5.1.2
      - annotated-types==0.6.0
      - anyio==3.7.1
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - backcall==0.2.0
      - backoff==2.2.1
      - backports-zoneinfo==0.2.1
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blinker==1.7.0
      - cachetools==5.3.2
      - certifi==2023.7.22
      - charset-normalizer==3.3.2
      - chroma-hnswlib==0.7.1
      - chromadb==0.3.29
      - click==8.1.7
      - clickhouse-connect==0.6.19
      - cloudpickle==3.0.0
      - coloredlogs==15.0.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - dataclasses-json==0.6.1
      - dearpygui==1.10.1
      - decorator==4.4.2
      - defusedxml==0.7.1
      - distro==1.9.0
      - docopt==0.6.2
      - duckdb==0.9.1
      - evdev==1.6.1
      - exceptiongroup==1.1.3
      - executing==2.0.1
      - farama-notifications==0.0.4
      - fastapi==0.85.1
      - fastjsonschema==2.19.1
      - ffmpy==0.3.1
      - filelock==3.13.1
      - flatbuffers==23.5.26
      - fonttools==4.44.0
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - gitdb==4.0.11
      - gitpython==3.1.41
      - gradio==3.47.1
      - gradio-client==0.6.0
      - graphlib-backport==1.0.3
      - greenlet==3.0.1
      - gymnasium==0.28.1
      - h11==0.14.0
      - highway-env==1.8.2
      - hnswlib==0.7.0
      - httpcore==1.0.1
      - httptools==0.6.1
      - httpx==0.25.1
      - huggingface-hub==0.21.3
      - humanfriendly==10.0
      - idna==3.4
      - imageio==2.32.0
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.1
      - ipython==8.12.3
      - jax-jumpy==1.0.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonpatch==1.33
      - jsonpointer==2.4
      - jsonschema==4.19.2
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.6.0
      - jupyter-core==5.7.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.5
      - langchain==0.0.331
      - langchain-community==0.0.14
      - langchain-core==0.1.14
      - langsmith==0.0.83
      - lxml==5.1.0
      - lz4==4.3.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - marshmallow==3.20.1
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mistune==3.0.2
      - monotonic==1.6
      - moviepy==1.0.3
      - mpmath==1.3.0
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - nbclient==0.9.0
      - nbconvert==7.16.1
      - nbformat==5.9.2
      - networkx==3.1
      - nltk==3.8.1
      - numpy==1.24.3
      - onnxruntime==1.16.1
      - openai==0.28.0
      - opencv-python==4.9.0.80
      - orjson==3.9.10
      - overrides==7.4.0
      - packaging==23.2
      - pandas==1.5.3
      - pandocfilters==1.5.1
      - parso==0.8.3
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.0.1
      - pipreqs==0.5.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.2.0
      - plotly==5.19.0
      - posthog==3.0.2
      - proglog==0.1.10
      - prompt-toolkit==3.0.43
      - protobuf==4.25.0
      - ptyprocess==0.7.0
      - pulsar-client==3.3.0
      - pure-eval==0.2.2
      - pyaml==23.12.0
      - pyarrow==15.0.0
      - pydantic==1.10.13
      - pydantic-core==2.10.1
      - pydeck==0.8.1b0
      - pydub==0.25.1
      - pygame==2.5.2
      - pygments==2.16.1
      - pynput==1.7.6
      - pyparsing==3.1.1
      - pypika==0.48.9
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-multipart==0.0.6
      - python-xlib==0.33
      - pytz==2023.3.post1
      - pyyaml==6.0
      - pyzmq==25.1.2
      - referencing==0.30.2
      - regex==2023.10.3
      - requests==2.31.0
      - retrying==1.3.4
      - rich==13.6.0
      - rpds-py==0.12.0
      - safetensors==0.4.2
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - semantic-version==2.10.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.2.0
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - sqlalchemy==2.0.15
      - stack-data==0.6.3
      - starlette==0.20.4
      - streamlit==1.30.0
      - sumolib==1.19.0
      - sympy==1.12
      - tenacity==8.2.3
      - threadpoolctl==3.3.0
      - tiktoken==0.5.1
      - tinycss2==1.2.1
      - tokenizers==0.15.2
      - toml==0.10.2
      - toolz==0.12.0
      - tornado==6.4
      - tqdm==4.66.1
      - traci==1.19.0
      - traitlets==5.14.1
      - typing-extensions==4.8.0
      - typing-inspect==0.9.0
      - tzdata==2023.4
      - tzlocal==5.2
      - urllib3==2.0.7
      - uvicorn==0.24.0.post1
      - uvloop==0.19.0
      - validators==0.22.0
      - watchdog==3.0.0
      - watchfiles==0.21.0
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - websockets==11.0.3
      - yarg==0.1.9
      - yarl==1.9.2
      - zipp==3.17.0
      - zstandard==0.22.0
